[package]
name = "machine"
version = "0.1.0"
authors = ["Kerollmops <renault.cle@gmail.com>"]

[dependencies]
log = "0.3"
env_logger = "0.3"
byteorder = "1.1"
core = { path = "../core" }

[features]
default = []
useless-param-codes = []
